# SPDX-FileCopyrightText: 2024 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: OpenSSF Scorecard analysis
on:
  push:
    branches:
      - main
  schedule:
    # Weekly on Wednesdays at 01:30 UTC
    - cron: "30 1 * * 3"

permissions:
  contents: read  # Best Security practice. Jobs only get read as base, and then permissions are added as needed

jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/.github/.github/workflows/security/openssf-scorecard.yml@feat/ci-refactor
